### PR TITLE
fix: Swift UserId and DeviceId setter

### LINKED ISSUE #282: Readonly properties hide setters from Swift
The `userId` and `deviceId` properties are declared as `readonly` in `Amplitude.h`:
```
/**
 Identifier for the current user.
 */
@property (nonatomic, copy, readonly) NSString *userId;

/**
 Identifier for the current device.
 */
@property (nonatomic, copy, readonly) NSString *deviceId;
```
Yet further down they also have setter methods declared:
```
/**
 Sets the userId.
 @param userId                  If your app has its own login system that you want to track users with, you can set the userId.
 @see [Setting Custom UserIds](https://github.com/amplitude/Amplitude-iOS#setting-custom-user-ids)
 */

- (void)setUserId:(NSString*) userId;
...
/**
 Sets the deviceId.

 **NOTE: not recommended unless you know what you are doing**

 @param deviceId                  If your app has its own system for tracking devices, you can set the deviceId.

 @see [Setting Custom Device Ids](https://github.com/amplitude/Amplitude-iOS#custom-device-ids)
 */
- (void)setDeviceId:(NSString*) deviceId;
```
These setter methods are inaccessible from Swift, because the ObjC→Swift bridging mechanism seems to prefer the `readonly` qualifier on the properties, thus hiding the setter methods.

## Expected Behavior
It should be possible to set the `userId` and `deviceId` properties from Swift.
## Current Behavior

It is not possible to set the `userId` and `deviceId` properties from Swift, because the setter methods are hidden by the `readonly` qualifiers at the property declarations.

## Possible Solution
Either rename these methods so they don't get mistaken for setters of readonly properties, or make the properties `readwrite` so they can be set from Swift using regular property assignment.

## Steps to Reproduce
Try calling `setUserId()` or `setDeviceId()` from Swift.

## Environment
- SDK Version: v6.0.0
- Device: any
- OS Version: any

### PR DESCRIPTION
**Pull request by jooohhn**
### Summary

- Move property declaration to `Amplitude.m` to fix usage in Swift
- Deprecate and document `setUserId(userId)` for `setUserId(userId, startNewSession)`
- Fixes #282 

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/master/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:

### CODE REVIEW

File: Sources/Amplitude/Amplitude.h [hunk 1]
```diff
@@ -541,15 +541,18 @@ typedef NSDictionary *_Nullable (^AMPLocationInfoBlock)(void);
  */
 
 /**
- Sets the userId.
+ Sets the userId and starts a new session.
+
+  **Note: this is deprecated** - please use `setUserId:(NSString*) userId startNewSession:(BOOL)startNewSession`
```
Comment (haoliu-amp) [inline Sources/Amplitude/Amplitude.h:546]: no space in between for `(NSString*) userId`

File: Sources/Amplitude/Amplitude.m [hunk 2]
```diff
@@ -87,6 +87,8 @@ @interface Amplitude()
 @property (nonatomic, assign) long long sessionId;
 @property (nonatomic, assign) BOOL backoffUpload;
 @property (nonatomic, assign) int backoffUploadBatchSize;
+@property (nonatomic, copy, readwrite, nullable) NSString *userId;
```
Comment (haoliu-amp) [inline Sources/Amplitude/Amplitude.m:90]: This will allow user to call setter without changing `readonly` for `userId` and `deviceId` inside `Amplitude.h`?

Comment (jooohhn) [reply Sources/Amplitude/Amplitude.m]: Changed so readwrite occurs in header instead of implementation

**Review by haoliu-amp — APPROVED** [review]
@jooohhn  You can merge if you verified 2 things-
1. Custom setter will be called.
2. Setter can both be accessed in objc and swift.

File: Sources/Amplitude/Amplitude.m (hunk 2 above)
Comment (jooohhn) [reply Sources/Amplitude/Amplitude.m]: Will revert so that we can solve the method syntax bug
